
[communicate]
  baseurl = "aaaaaa"

[database]
  address = "./conf/data.db"
  type = "sqlite"

[logger]
  level = "debug"

[server]
  port = 8080
  pause=false

[xxqg]
  expirenotify = false
  schema = "https://scintillating-axolotl-8c8432.netlify.app/?"
