[server]
port=8080
token=""

# 客户端需要
[database]
type="sqlite"
address="./conf/data.db"

[logger]
level="debug"

# 客户端需要
[xxqg]
schema="https://scintillating-axolotl-8c8432.netlify.app/?"
expireNotify=true # 失效是否通知，默认不通知

# 客户端需要
[communicate]
baseUrl=""

# 服务端需要
[dingtalk]
agentId=""
appKey=""
appSecret=""
accessToken=""